# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit autoupdate
exclude: '^(.tox/|.*\.sh$|.*\.html$)'
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      - id: check-xml
      - id: check-yaml
      #  exclude: '.pep8speaks.yml'

  #- repo: https://gitlab.com/pycqa/flake8
    #rev: 3.9.2
    #hooks:
      #- id: flake8
        #args: ["--max-line-length=102"]
        #additional_dependencies: ["flake8-bugbear"]
        #files: main.py

  #- repo: https://github.com/weibullguy/pycodestyle
    #rev: '2.6.1'
    #hooks:
      #- id: pycodestyle
        #args: ["--max-line-length=102"]
        #files: main.py

  #- repo: https://github.com/lovesegfault/beautysh
    #rev: v6.2.1
    #hooks:
      #- id: beautysh
