product: gentoo2
full_name: Gentoo 2
type: platform

benchmark_root: "../../linux_os/guide"

components_root: "../../components"

profiles_root: "./profiles"

pkg_manager: "portage"

init_system: "openrc"

cpes_root: "../../shared/applicability"
cpes:
  new_product:
    name: "cpe:/o:gentoo:2"
    title: "Gentoo 2"
    check_id: installed_OS_is_gentoo2

reference_uris:
  cis: 'https://benchmarks.cisecurity.org/tools2/linux/CIS_Gentoo_Benchmark_v1.0.pdf'
